spring:
  main:
    web-application-type: servlet
  sql:
    init:
      mode: always
  application:
    name: PRI
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    schemas: employees
    baselineOnMigrate: true
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/java_db?currentSchema=test25
    username: api
    password: api
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariPool
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true        # Fix: use colon not = and no trailing colon
        default_schema: test25
    defer-datasource-initialization: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG             # Fix: colon allows correct parsing

server:
  port: 8082                 # Fix: simple key-value syntax

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs

thesis-module:
  generate-theses-and-chapters-on-startup: false
