spring:
  sql:
    init:
      mode: always
  application:
    name: PRI
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    schemas: employees
    baselineOnMigrate: true
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/java_db?currentSchema=test25
    username: api
    password: api
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariPool
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql=true:
        default_schema: test25
    defer-datasource-initialization: true
logging:
  level:
    org:
      hibernate:
        SQL=DEBUG:
server:
  port:
    8082
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
thesis-module:
  generate-theses-and-chapters-on-startup: false